name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        pushd loxrun
        cargo build --verbose
        popd
    - name: Run tests
      run: |
        pushd loxrun
        cargo test --verbose
        popd
    - name: Install Dart
      run: |
        bash ${GITHUB_WORKSPACE}/scripts/post_setup.sh
    - name: Run verification
      run: |
        git clone https://github.com/munificent/craftinginterpreters.git verification/testsuite
        pushd verification/testsuite
        git apply ../dart-upgrade.patch
        pushd tool
        dart pub get
        popd
        dart tool/bin/test.dart chap08_statements -i ../../loxrun/target/debug/loxrun
        dart tool/bin/test.dart chap09_control -i ../../loxrun/target/debug/loxrun
        dart tool/bin/test.dart chap10_functions -i ../../loxrun/target/debug/loxrun
        dart tool/bin/test.dart chap11_resolving -i ../../loxrun/target/debug/loxrun
        dart tool/bin/test.dart chap12_classes -i ../../loxrun/target/debug/loxrun
        popd
